# **Part 1: Theoretical Question.**
**1. What are the different data structures used in Tensorflow?. Give some examples.**

TensorFlow, an open-source machine learning library, primarily uses tensors as the fundamental data structure. A tensor is a multi-dimensional array that can represent various types of data. While tensors are the core data structure, TensorFlow provides other data structures and abstractions to support different aspects of machine learning tasks

Example:

import tensorflow as tf

- Creating a tensor
- tensor_a = tf.constant([[1, 2, 3], [4, 5, 6]])


**2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.**

In TensorFlow, both constants and variables are used to represent data, but they have key differences in terms of mutability and usage in the context of building and training models.

**TensorFlow Constant:**

- **Immutability:** Constants are immutable, meaning their values cannot be changed after they are assigned.
- **Use Case:** Constants are typically used for representing fixed values that remain constant throughout the execution of a program.
- **Example:**




In [1]:
import tensorflow as tf

# Creating a TensorFlow constant
constant_tensor = tf.constant([1, 2, 3])


In [2]:
constant_tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

**TensorFlow Variable:**

- **Mutability:** Variables are mutable, and their values can be changed during training. They are often used to represent trainable parameters in a model.
- **Use Case:** Variables are used for parameters that need to be updated during optimization, such as weights and biases in a neural network.
- **Example:**
  

In [3]:
import tensorflow as tf

# Creating a TensorFlow variable
initial_value = tf.constant([1, 2, 3])
variable_tensor = tf.Variable(initial_value)


In [4]:
variable_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [6]:
import tensorflow as tf

# Creating a TensorFlow constant
constant_tensor = tf.constant([1, 2, 3])

# Creating a TensorFlow variable
initial_value = tf.constant([4, 5, 6])
variable_tensor = tf.Variable(initial_value)

# Printing the values
print("Constant Tensor:", constant_tensor.numpy())
print("Variable Tensor (Before Update):", variable_tensor.numpy())

# Modifying the variable tensor
variable_tensor.assign([7, 8, 9])

# Printing the values after modification
print("Variable Tensor (After Update):", variable_tensor.numpy())


Constant Tensor: [1 2 3]
Variable Tensor (Before Update): [4 5 6]
Variable Tensor (After Update): [7 8 9]


In [7]:
# Attempting to modify the constant tensor (will result in an error)
constant_tensor.assign([7, 8, 9])  # Uncommenting this line will raise an error


**3. Describe the process of matrix addition, multiplication, and elements wise operations in TensorFlow.**

**Matrix Addition:**
Matrix addition is performed element-wise, where corresponding elements in two matrices are added together to form a new matrix. The matrices must have the same dimensions.

**Example:**

In [8]:
import tensorflow as tf

# Create two matrices
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])

# Perform matrix addition
matrix_sum = tf.add(matrix_a, matrix_b)

# Display the result
print("Matrix A:\n", matrix_a.numpy())
print("Matrix B:\n", matrix_b.numpy())
print("Matrix Sum (A + B):\n", matrix_sum.numpy())


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix Sum (A + B):
 [[ 6  8]
 [10 12]]


**Matrix Multiplication:**

Matrix multiplication involves the dot product of rows and columns. The number of columns in the first matrix must be equal to the number of rows in the second matrix for the multiplication to be defined.

**Example:**

In [9]:
import tensorflow as tf

# Create two matrices
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])

# Perform matrix multiplication
matrix_product = tf.matmul(matrix_a, matrix_b)

# Display the result
print("Matrix A:\n", matrix_a.numpy())
print("Matrix B:\n", matrix_b.numpy())
print("Matrix Product (A * B):\n", matrix_product.numpy())


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix Product (A * B):
 [[19 22]
 [43 50]]


**Element-wise Operations:**
Element-wise operations involve performing an operation on corresponding elements of two tensors. These operations can include addition, subtraction, multiplication, division, and more.

**Example:**

In [10]:
import tensorflow as tf

# Create two tensors
tensor_a = tf.constant([[1, 2], [3, 4]])
tensor_b = tf.constant([[5, 6], [7, 8]])

# Perform element-wise addition
elementwise_sum = tf.add(tensor_a, tensor_b)

# Perform element-wise multiplication
elementwise_product = tf.multiply(tensor_a, tensor_b)

# Display the results
print("Tensor A:\n", tensor_a.numpy())
print("Tensor B:\n", tensor_b.numpy())
print("Element-wise Sum (A + B):\n", elementwise_sum.numpy())
print("Element-wise Product (A * B):\n", elementwise_product.numpy())


Tensor A:
 [[1 2]
 [3 4]]
Tensor B:
 [[5 6]
 [7 8]]
Element-wise Sum (A + B):
 [[ 6  8]
 [10 12]]
Element-wise Product (A * B):
 [[ 5 12]
 [21 32]]


# **Part 2: Practical Implementation**
### **Task 1: Creating and Manipulating Matrice.**
**1. Create a normal matrix A with dimensions 3x3, using TensorFlow's random_normal function. Display the values of matrix A.**

In [16]:
import tensorflow as tf

# Create a 2x2 matrix with random values from a normal distribution
matrix_A = tf.random.normal(shape=(3, 3))

# Display the values of matrix A
print("Matrix A:\n", matrix_A.numpy())


Matrix A:
 [[ 1.4986585  -0.20172824 -0.39333636]
 [ 0.4572874   2.0150108   1.2711082 ]
 [-0.12992634 -0.5970167  -0.2042668 ]]


**2. Create a Gaussian matrix B with dimensions 4x4, using TensorFlow's truncated_normal function. Display the values of matrix B.**

In [17]:
import tensorflow as tf

# Specify the dimensions of the matrix (replace 'x' with the desired size)
matrix_dimensions = (4, 4)  # For example, a 4x4 matrix

# Create a matrix with random values from a truncated normal distribution
matrix_B = tf.random.truncated_normal(shape=matrix_dimensions, mean=0.0, stddev=1.0)

# Display the values of matrix B
print("Matrix B:\n", matrix_B.numpy())


Matrix B:
 [[-1.3789437   0.4581161   0.7321869  -0.13655604]
 [-0.35626748  0.03861269  0.6407998   0.05932369]
 [ 0.33066976 -0.10562874 -0.6122653  -1.924805  ]
 [-0.57354325  0.6583181  -0.30191398  0.16447009]]


**3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 2 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C.**

In [13]:
import tensorflow as tf

# Create a 2x2 matrix with values from a normal distribution with specified mean and stddev
matrix_C = tf.random.normal(shape=(2, 2), mean=2.0, stddev=0.5)

# Display the values of matrix C
print("Matrix C:\n", matrix_C.numpy())


Matrix C:
 [[1.6310446 2.4484496]
 [1.4197941 2.41125  ]]


**4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D.**

In [19]:
import tensorflow as tf

# Assuming you have matrices A and B
matrix_A = tf.random.normal(shape=(2, 2))
matrix_B = tf.random.truncated_normal(shape=(2, 2), mean=0.0, stddev=1.0)

# Perform matrix addition
matrix_D = tf.add(matrix_A, matrix_B)

# Display the values of matrices A, B, and the result matrix D
print("Matrix A:\n", matrix_A.numpy())
print("Matrix B:\n", matrix_B.numpy())
print("Matrix D (Result of A + B):\n", matrix_D.numpy())


Matrix A:
 [[ 1.1731125 -1.0838125]
 [-0.3697052 -0.5110007]]
Matrix B:
 [[ 1.603976   0.9365206]
 [ 1.1074717 -1.1832938]]
Matrix D (Result of A + B):
 [[ 2.7770886 -0.1472919]
 [ 0.7377665 -1.6942945]]


**5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.**

In [20]:
matrix_E = tf.matmul(matrix_C, matrix_D)

# Display the values of matrices C, D, and E
print("Matrix C:\n", matrix_C.numpy())
print("Matrix D:\n", matrix_D.numpy())
print("Matrix E (C * D):\n", matrix_E.numpy())

Matrix C:
 [[1.6310446 2.4484496]
 [1.4197941 2.41125  ]]
Matrix D:
 [[ 2.7770886 -0.1472919]
 [ 0.7377665 -1.6942945]]
Matrix E (C * D):
 [[ 6.3359394 -4.388634 ]
 [ 5.7218337 -4.294492 ]]


# **Task 2: Performing Additional Matrix Operation.**
**1. Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform function.**

In [21]:


# Create a 2x2 matrix with random values from a uniform distribution
matrix_F = tf.random.uniform(shape=(2, 2))

# Display the values of matrix F
print("Matrix F:\n", matrix_F.numpy())


Matrix F:
 [[0.12903309 0.77613294]
 [0.32586932 0.68353283]]


**2. Calculate the transpose of matrix F and store the result in matrix G.**

In [22]:
# Matrix F
matrix_F = tf.random.uniform(shape=(2, 2))

# Calculate the transpose and store the result in matrix G
matrix_G = tf.transpose(matrix_F)

# Display the values of matrices F and G
print("Matrix F:\n", matrix_F.numpy())
print("Matrix G (Transpose of F):\n", matrix_G.numpy())


Matrix F:
 [[0.21425188 0.9705292 ]
 [0.813455   0.06153953]]
Matrix G (Transpose of F):
 [[0.21425188 0.813455  ]
 [0.9705292  0.06153953]]


**3. Calculate the elements wise exponential of matrix F and store the result in matrix H.**

In [23]:
matrix_H = tf.exp(matrix_F)

# Display the values of matrices F and H
print("Matrix F:\n", matrix_F.numpy())
print("Matrix H (Element-wise Exponential of F):\n", matrix_H.numpy())

Matrix F:
 [[0.21425188 0.9705292 ]
 [0.813455   0.06153953]]
Matrix H (Element-wise Exponential of F):
 [[1.2389346 2.6393409]
 [2.255688  1.0634725]]


**4. Create a matrix I by concatenating matrix F and matrix G horizontally.**

In [24]:
# Concatenate matrices F and G horizontally
matrix_I = tf.concat([matrix_F, matrix_G], axis=1)

# Display the values of matrices F, G, and I
print("Matrix F:\n", matrix_F.numpy())
print("Matrix G (Transpose of F):\n", matrix_G.numpy())
print("Matrix I (Concatenation of F and G horizontally):\n", matrix_I.numpy())

Matrix F:
 [[0.21425188 0.9705292 ]
 [0.813455   0.06153953]]
Matrix G (Transpose of F):
 [[0.21425188 0.813455  ]
 [0.9705292  0.06153953]]
Matrix I (Concatenation of F and G horizontally):
 [[0.21425188 0.9705292  0.21425188 0.813455  ]
 [0.813455   0.06153953 0.9705292  0.06153953]]


**5. Create a matrix J by concatenating matrix F and matrix H vertically.**

In [25]:
# Concatenate matrices F and H vertically
matrix_J = tf.concat([matrix_F, matrix_H], axis=0)

# Display the values of matrices F, H, and J
print("Matrix F:\n", matrix_F.numpy())
print("Matrix H (Element-wise Exponential of F):\n", matrix_H.numpy())
print("Matrix J (Concatenation of F and H vertically):\n", matrix_J.numpy())

Matrix F:
 [[0.21425188 0.9705292 ]
 [0.813455   0.06153953]]
Matrix H (Element-wise Exponential of F):
 [[1.2389346 2.6393409]
 [2.255688  1.0634725]]
Matrix J (Concatenation of F and H vertically):
 [[0.21425188 0.9705292 ]
 [0.813455   0.06153953]
 [1.2389346  2.6393409 ]
 [2.255688   1.0634725 ]]
